In [2]:
import pandas as pd
import numpy as np

## check percentiles

In [3]:
dataframe = pd.read_csv('../database/train/1st_phase_mbf_data.csv')
dataframe.describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6,0.7, 0.8, 0.9])

,isdn,partition_n_0,revenue_n_1,arpu_n_1,td_thoai_n_1,value_thoai_n_1,td_data_n_1,value_data_n_1,revenue_n_2,arpu_n_2,...,duration_n_1,duration_n_2,revenue_n_1_to_n_2,td_thoai_n_1_to_n_2,value_thoai_n_1_to_n_2,td_data_n_1_to_n_2,value_data_n_1_to_n_2,segment_n_1,segment_n_2,cycle_changed?
count,5.198480e+05,519848.0,5.198480e+05,5.198480e+05,5.198480e+05,5.198480e+05,5.198480e+05,5.198480e+05,5.198480e+05,5.198480e+05,...,519848.000000,519848.000000,519848.000000,519848.000000,519848.000000,519848.000000,5.198480e+05,519848.000000,519848.000000,519848.000000
mean,8.883857e+08,20231201.0,2.524187e+05,2.431307e+05,6.715994e+04,6.130769e+03,1.417059e+05,2.258750e+10,2.427689e+05,2.376628e+05,...,2.548785,3.485423,8.549192,3.133092,2.713750,3.943699,7.017979e+03,8.935587,8.932711,0.256394
std,6.848775e+07,0.0,1.990515e+05,1.791890e+05,9.880911e+04,1.374148e+04,1.058865e+05,3.846161e+10,1.988304e+05,1.805486e+05,...,3.647375,4.396628,1402.941623,389.154423,80.303940,382.217130,7.396978e+05,0.665458,0.679617,0.436642
min,7.020007e+08,20231201.0,-1.822000e+06,-2.009678e+06,-4.617523e+05,0.000000e+00,-1.822000e+06,0.000000e+00,-2.103035e+06,-2.104011e+06,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000
10%,7.761986e+08,20231201.0,9.652400e+04,9.251440e+04,0.000000e+00,1.800000e+01,5.500000e+04,7.055115e+08,8.389970e+04,8.088000e+04,...,1.000000,1.000000,0.758872,0.000000,0.096434,0.775278,4.052572e-01,9.000000,9.000000,0.000000
20%,7.990249e+08,20231201.0,1.285714e+05,1.229200e+05,2.160000e+03,2.720000e+02,7.135000e+04,2.924761e+09,1.134000e+05,1.122160e+05,...,1.000000,1.000000,0.906669,0.433533,0.454545,1.000000,6.493440e-01,9.000000,9.000000,0.000000
30%,9.023780e+08,20231201.0,1.590000e+05,1.569921e+05,7.048000e+03,7.300000e+02,9.000000e+04,5.381201e+09,1.507000e+05,1.474620e+05,...,1.000000,1.000000,0.969038,0.815645,0.640422,1.000000,7.969215e-01,9.000000,9.000000,0.000000
40%,9.040182e+08,20231201.0,1.788168e+05,1.711486e+05,1.728700e+04,1.424000e+03,9.997700e+04,8.233902e+09,1.680500e+05,1.665830e+05,...,1.000000,1.000000,0.994246,0.983889,0.787281,1.000000,9.157105e-01,9.000000,9.000000,0.000000
50%,9.062520e+08,20231201.0,2.099995e+05,2.016660e+05,2.770800e+04,2.391000e+03,1.194450e+05,1.178290e+10,2.000000e+05,1.967995e+05,...,1.000000,1.000000,1.000000,1.000000,0.925707,1.000000,1.018153e+00,9.000000,9.000000,0.000000
60%,9.085613e+08,20231201.0,2.477974e+05,2.359810e+05,5.463000e+04,3.732200e+03,1.431000e+05,1.642624e+10,2.349174e+05,2.310564e+05,...,1.000000,1.000000,1.013938,1.000000,1.036964,1.000000,1.144000e+00,9.000000,9.000000,0.000000
70%,9.316723e+08,20231201.0,2.894359e+05,2.796240e+05,9.012780e+04,5.692000e+03,1.590000e+05,2.305812e+10,2.800248e+05,2.757660e+05,...,1.000000,1.000000,1.062859,1.000000,1.231852,1.000000,1.313521e+00,9.000000,9.000000,0.000000
80%,9.346397e+08,20231201.0,3.417921e+05,3.338630e+05,1.149719e+05,8.950000e+03,1.940000e+05,3.365943e+10,3.354839e+05,3.310950e+05,...,1.000000,6.000000,1.204923,1.117142,1.540733,1.043333,1.597265e+00,9.000000,9.000000,1.000000
90%,9.377744e+08,20231201.0,4.408453e+05,4.279660e+05,1.710000e+05,1.577800e+04,2.500000e+05,5.536913e+10,4.348603e+05,4.271040e+05,...,12.000000,12.000000,1.662506,1.825692,2.310091,1.724518,2.373746e+00,9.000000,9.000000,1.000000
max,1.211495e+09,20231201.0,1.817189e+07,1.625354e+07,5.368206e+06,2.002078e+06,1.028879e+07,6.788854e+12,1.543292e+07,1.672897e+07,...,12.000000,12.000000,684072.750000,218907.500000,22499.000000,193048.888889,2.949420e+08,9.000000,9.000000,1.000000

In [4]:
dataframe = dataframe.drop(columns=['isdn', 'main_package_n_0', 'main_package_n_1', 'register_service_n_2', 'partition_n_0'])
columns = list(dataframe.columns)

In [5]:
describe_df = dataframe.describe(percentiles=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6,0.7, 0.8, 0.9])

In [6]:
used_data = dataframe.copy()
for col in columns:
    used_data = used_data[(used_data[col] >= describe_df[col]['10%']) & (used_data[col] <= describe_df[col]['90%'])]


used_data.columns

Index(['revenue_n_1', 'arpu_n_1', 'td_thoai_n_1', 'value_thoai_n_1',
       'td_data_n_1', 'value_data_n_1', 'revenue_n_2', 'arpu_n_2',
       'td_thoai_n_2', 'value_thoai_n_2', 'td_data_n_2', 'value_data_n_2',
       'duration_n_0', 'duration_n_1', 'duration_n_2', 'revenue_n_1_to_n_2',
       'td_thoai_n_1_to_n_2', 'value_thoai_n_1_to_n_2', 'td_data_n_1_to_n_2',
       'value_data_n_1_to_n_2', 'segment_n_1', 'segment_n_2',
       'cycle_changed?'],
      dtype='object')

In [7]:
used_data['cycle_changed?'].value_counts()

0    89224
1    29125
Name: cycle_changed?, dtype: int64

In [14]:
used_data.to_csv('../database/train/train_1st.csv', index=False)

## check distribution

In [10]:
eda_data = used_data.copy()
eda_data['cycle_change_n_1'] = [1 if x != y else 0 for x, y in zip(eda_data['duration_n_1'], eda_data['duration_n_2'])]

In [11]:
eda_data['cycle_change_n_1'].value_counts()

0    107402
1     10947
Name: cycle_change_n_1, dtype: int64

In [12]:
eda_data['cycle_changed?'].value_counts()

0    89224
1    29125
Name: cycle_changed?, dtype: int64

In [14]:
cycle_changed = eda_data[['cycle_change_n_1', 'cycle_changed?']]
cycle_changed_corr = cycle_changed.corr()
print(cycle_changed_corr)

                  cycle_change_n_1  cycle_changed?
cycle_change_n_1          1.000000        0.430417
cycle_changed?            0.430417        1.000000

In [15]:
eda_data.to_csv('../database/train_1st_eda.csv', index=False)

## Plot anything

In [17]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()
scaled_df = eda_data.copy()
scale_cols =  ['revenue_n_1', 'arpu_n_1', 'td_thoai_n_1',
       'value_thoai_n_1', 'td_data_n_1', 'value_data_n_1', 'revenue_n_2',
       'arpu_n_2', 'td_thoai_n_2', 'value_thoai_n_2', 'td_data_n_2', 'value_data_n_2',
       'revenue_n_1_to_n_2', 'td_thoai_n_1_to_n_2', 'value_thoai_n_1_to_n_2', 'td_data_n_1_to_n_2', 'value_data_n_1_to_n_2']
scaled_df[scale_cols] = scaler.fit_transform(scaled_df[scale_cols])

scaled_df.describe()

,revenue_n_1,arpu_n_1,td_thoai_n_1,value_thoai_n_1,td_data_n_1,value_data_n_1,revenue_n_2,arpu_n_2,td_thoai_n_2,value_thoai_n_2,...,duration_n_2,revenue_n_1_to_n_2,td_thoai_n_1_to_n_2,value_thoai_n_1_to_n_2,td_data_n_1_to_n_2,value_data_n_1_to_n_2,segment_n_1,segment_n_2,cycle_changed?,cycle_change_n_1
count,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,...,118349.000000,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,1.183490e+05,118349.0,118349.0,118349.000000,118349.000000
mean,-5.571519e-17,-4.706973e-17,-1.248789e-17,-3.530229e-17,-8.993680e-17,6.916368e-17,1.412092e-16,-1.181546e-16,1.354455e-16,6.099852e-17,...,3.482623,-1.167017e-15,1.911607e-16,1.472130e-16,3.639498e-16,6.469085e-16,9.0,9.0,0.246094,0.092498
std,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,...,4.355158,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,1.000004e+00,0.0,0.0,0.430736,0.289728
min,-1.615534e+00,-1.671981e+00,-1.025553e+00,-1.073292e+00,-1.610425e+00,-1.169231e+00,-1.770364e+00,-1.773125e+00,-1.060589e+00,-1.135442e+00,...,1.000000,-2.301767e+00,-2.363600e+00,-1.902641e+00,-2.385450e+00,-1.657830e+00,9.0,9.0,0.000000,0.000000
25%,-7.183077e-01,-7.110507e-01,-8.962465e-01,-7.736500e-01,-7.945190e-01,-7.827898e-01,-7.080059e-01,-7.005888e-01,-8.539513e-01,-7.757893e-01,...,1.000000,-3.793781e-01,-3.882411e-03,-7.210803e-01,-1.998708e-01,-7.249019e-01,9.0,9.0,0.000000,0.000000
50%,-1.529185e-01,-1.506002e-01,-4.805261e-01,-3.134324e-01,-1.353772e-01,-3.014252e-01,-1.435499e-01,-1.561537e-01,-4.328584e-01,-2.959685e-01,...,1.000000,-9.108308e-02,3.615923e-01,-1.317275e-01,-1.998708e-01,-1.647458e-01,9.0,9.0,0.000000,0.000000
75%,6.717044e-01,6.836472e-01,9.864246e-01,4.853191e-01,7.934762e-01,5.329427e-01,6.770979e-01,6.786313e-01,9.529023e-01,5.031647e-01,...,6.000000,1.529389e-01,3.615923e-01,5.888752e-01,-1.998708e-01,5.474925e-01,9.0,9.0,0.000000,0.000000
max,3.241924e+00,3.077264e+00,2.380864e+00,3.566596e+00,2.896889e+00,3.275001e+00,3.146457e+00,2.927245e+00,2.371192e+00,3.432089e+00,...,12.000000,5.982191e+00,2.611763e+00,2.954212e+00,6.845570e+00,3.110568e+00,9.0,9.0,1.000000,1.000000